# Generated by Django 6.0.3 on 2026-09-06 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('tenant', '0002_alter_tenant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='tenant.tenant'),
            preserve_default=False,
        ),
    ]
