# Generated by Django 6.1.1 on 2026-09-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brand_tenant_required'),
        ('tenant', '0002_alter_tenant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='brand_shop_name'),
        ),
    ]
