# Generated by Django 6.1.1 on 2026-09-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_alter_brand_name_brand_brand_shop_name'),
        ('category', '0002_alter_category_name_alter_category_slug_and_more'),
        ('product', '0001_initial'),
        ('tenant', '0002_alter_tenant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('ARCHIVED', 'Archived')], default='AVAILABLE', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='brand.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='category.category')),
                ('product_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.productline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenant.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'sku'), name='product_shop_sku'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_nonnegative')],
            },
        ),
    ]
