# Generated by Django 6.1.1 on 2026-09-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdSequence',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
